name: build_pat

on:
  push:
    paths-ignore:
      - ".dev_scripts/**"
      - ".github/**.md"
      - "demo/**"
      - "docker/**"
      - "docs/**"
      - "docs_zh-CN/**"
      - "tools/**"
      - "README.md"
      - "README_zh-CN.md"

  pull_request:
    paths-ignore:
      - ".dev_scripts/**"
      - ".github/**.md"
      - "demo/**"
      - "docker/**"
      - "docs/**"
      - "docs_zh-CN/**"
      - "tools/**"
      - "README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_parrots:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cokedong/parrots:pat0.21.0a0_cuda11
      credentials:
        username: cokedong
        password: ${{ secrets.PARROTS_CI_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install mmdet dependencies
        run: |
          source /usr/local/env/pat_latest
          git clone https://github.com/open-mmlab/mmcv.git && cd mmcv
          MMCV_WITH_OPS=1 python setup.py install
          cd .. && rm -rf mmcv
          python -c 'import mmcv; print(mmcv.__version__)'
          pip install -r requirements.txt
      - name: Build and install
        run: rm -rf .eggs && pip install -e .
